# Travis CI file

language: python
python:
    - "2.7"

# Setup environment variables
# env:    
#    - DATABASE_URL="postgresql://postgres:@localhost/blogful_test" TEST_DATABASE_URL="postgresql://postgres:@localhost/blogful_test" SECRET_KEY="1234567890"
    
# Install dependencies    
install: pip install -r requirements.txt

# Setup test database
before_script:
    - psql -c 'create database blogful_test;' -U postgres
    
# Test scripts    
script:
    - PYTHONPATH=. python tests/test_filter.py
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py
    